repos:
  - repo: local
    hooks:
      - id: format
        name: ruff format
        entry: uv run ruff format src/app_name
        language: system
        pass_filenames: false
        types: [python]
      - id: lint
        name: ruff lint
        entry: uv run ruff check src/app_name --fix
        language: system
        pass_filenames: false
        types: [python]
